<?php

$countryCodes = array(
    // A
    'AW' => 'Aruba 🇦🇼',
    'AF' => 'Afghanistan 🇦🇫',
    'AO' => 'Angola 🇦🇴',
    'AL' => 'Albania 🇦🇱',
    'AD' => 'Andorra 🇦🇩',
    'AE' => 'United Arab Emirates 🇦🇪',
    'AR' => 'Argentina 🇦🇷',
    'AM' => 'Armenia 🇦🇲',
    'AS' => 'American Samoa 🇦🇸',
    'AG' => 'Antigua and Barbuda 🇦🇬',
    'AU' => 'Australia 🇦🇺',
    'AT' => 'Austria 🇦🇹',
    'AZ' => 'Azerbaijan 🇦🇿',
    // B
    'BI' => 'Burundi 🇧🇮',
    'BE' => 'Belgium 🇧🇪',
    'BJ' => 'Benin 🇧🇯',
    'BF' => 'Burkina Faso 🇧🇫',
    'BD' => 'Bangladesh 🇧🇩',
    'BG' => 'Bulgaria 🇧🇬',
    'BH' => 'Bahrain 🇧🇭',
    'BS' => 'Bahamas 🇧🇸',
    'BA' => 'Bosnia and Herzegovina 🇧🇦',
    'BY' => 'Belarus 🇧🇾',
    'BZ' => 'Belize 🇧🇿',
    'BM' => 'Bermuda 🇧🇲',
    'BO' => 'Bolivia 🇧🇴',
    'BR' => 'Brazil 🇧🇷',
    'BB' => 'Barbados 🇧🇧',
    'BN' => 'Brunei Darussalam 🇧🇳',
    'BT' => 'Bhutan 🇧🇹',
    'BW' => 'Botswana 🇧🇼',
    // C
    'CF' => 'Central African Republic 🇨🇫',
    'CA' => 'Canada 🇨🇦',
    'CH' => 'Switzerland 🇨🇭',
    'JG' => 'Channel Islands',
    'CL' => 'Chile 🇨🇱',
    'CN' => 'China 🇨🇳',
    'CI' => 'Cote d\'Ivoire 🇨🇮',
    'CM' => 'Cameroon 🇨🇲',
    'CD' => 'Congo, Dem. Rep. 🇨🇩',
    'CG' => 'Congo, Rep. 🇨🇬',
    'CO' => 'Colombia 🇨🇴',
    'KM' => 'Comoros 🇰🇲',
    'CV' => 'Cabo Verde 🇨🇻',
    'CR' => 'Costa Rica 🇨🇷',
    'CU' => 'Cuba 🇨🇺',
    'CW' => 'Curacao 🇨🇼',
    'KY' => 'Cayman Islands 🇰🇾',
    'CY' => 'Cyprus 🇨🇾',
    'CZ' => 'Czech Republic 🇨🇿',
    // D
    'DE' => 'Germany 🇩🇪',
    'DJ' => 'Djibouti 🇩🇯',
    'DM' => 'Dominica 🇩🇲',
    'DK' => 'Denmark 🇩🇰',
    'DO' => 'Dominican Republic 🇩🇴',
    'DZ' => 'Algeria 🇩🇿',
    // E
    'EC' => 'Ecuador 🇪🇨',
    'EG' => 'Egypt, Arab Rep. 🇪🇬',
    'ER' => 'Eritrea 🇪🇷',
    'ES' => 'Spain 🇪🇸',
    'EE' => 'Estonia 🇪🇪',
    'ET' => 'Ethiopia 🇪🇹',
    // F
    'FI' => 'Finland 🇫🇮',
    'FJ' => 'Fiji 🇫🇯',
    'FR' => 'France 🇫🇷',
    'WF' => 'French Southern and Antarctic Lands 🇹🇫',
    'FO' => 'Faroe Islands 🇫🇴',
    'FM' => 'Micronesia, Fed. Sts. 🇫🇲',
    // G
    'GA' => 'Gabon 🇬🇦',
    'GB' => 'United Kingdom 🇬🇧',
    'GE' => 'Georgia 🇬🇪',
    'GH' => 'Ghana 🇬🇭',
    'GI' => 'Gibraltar 🇬🇮',
    'GN' => 'Guinea 🇬🇳',
    'GM' => 'Gambia, The 🇬🇲',
    'GW' => 'Guinea-Bissau 🇬🇼',
    'GQ' => 'Equatorial Guinea 🇬🇶',
    'GR' => 'Greece 🇬🇷',
    'GD' => 'Grenada 🇬🇩',
    'GL' => 'Greenland 🇬🇱',
    'GT' => 'Guatemala 🇬🇹',
    'GU' => 'Guam 🇬🇺',
    'GY' => 'Guyana 🇬🇾',
    // H
    'HK' => 'Hong Kong SAR, China 🇭🇰',
    'HN' => 'Honduras 🇭🇳',
    'HR' => 'Croatia 🇭🇷',
    'HT' => 'Haiti 🇭🇹',
    'HU' => 'Hungary 🇭🇺',
    // I
    'ID' => 'Indonesia 🇮🇩',
    'IM' => 'Isle of Man 🇮🇲',
    'IN' => 'India 🇮🇳',
    'IE' => 'Ireland 🇮🇪',
    'IR' => 'Iran, Islamic Rep. 🇮🇷',
    'IQ' => 'Iraq 🇮🇶',
    'IS' => 'Iceland 🇮🇸',
    'IL' => 'Israel 🇮🇱',
    'IT' => 'Italy 🇮🇹',
    // J
    'JM' => 'Jamaica 🇯🇲',
    'JO' => 'Jordan 🇯🇴',
    'JP' => 'Japan 🇯🇵',
    // K
    'KZ' => 'Kazakhstan 🇰🇿',
    'KE' => 'Kenya 🇰🇪',
    'KG' => 'Kyrgyz Republic 🇰🇬',
    'KH' => 'Cambodia 🇰🇭',
    'KI' => 'Kiribati 🇰🇮',
    'KN' => 'St. Kitts and Nevis 🇰🇳',
    'KR' => 'South Korea. 🇰🇷',
    'KW' => 'Kuwait 🇰🇼',
    // L
    'LA' => 'Laos PDR 🇱🇦',
    'LB' => 'Lebanon 🇱🇧',
    'LR' => 'Liberia 🇱🇷',
    'LY' => 'Libya 🇱🇾',
    'LC' => 'St. Lucia 🇱🇨',
    'LI' => 'Liechtenstein 🇱🇮',
    'LK' => 'Sri Lanka 🇱🇰',
    'LS' => 'Lesotho 🇱🇸',
    'LT' => 'Lithuania 🇱🇹',
    'LU' => 'Luxembourg 🇱🇺',
    'LV' => 'Latvia 🇱🇻',
    // M
    'MO' => 'Macao SAR, China 🇲🇴',
    'MF' => 'St. Martin (French part) 🇲🇫',
    'MA' => 'Morocco 🇲🇦',
    'MC' => 'Monaco 🇲🇨',
    'MD' => 'Moldova 🇲🇩',
    'MG' => 'Madagascar 🇲🇬',
    'MV' => 'Maldives 🇲🇻',
    'MX' => 'Mexico 🇲🇽',
    'MH' => 'Marshall Islands 🇲🇭',
    'MK' => 'Macedonia, FYR 🇲🇰',
    'ML' => 'Mali 🇲🇱',
    'MT' => 'Malta 🇲🇹',
    'MM' => 'Myanmar 🇲🇲',
    'ME' => 'Montenegro 🇲🇪',
    'MN' => 'Mongolia 🇲🇳',
    'MP' => 'Northern Mariana Islands 🇲🇵',
    'MZ' => 'Mozambique 🇲🇿',
    'MR' => 'Mauritania 🇲🇷',
    'MU' => 'Mauritius 🇲🇺',
    'MW' => 'Malawi 🇲🇼',
    // N
    'MY' => 'Malaysia 🇲🇾',
    'NA' => 'Namibia 🇳🇦',
    'NC' => 'New Caledonia 🇳🇨',
    'NE' => 'Niger 🇳🇪',
    'NG' => 'Nigeria 🇳🇬',
    'NI' => 'Nicaragua 🇳🇮',
    'NL' => 'Netherlands 🇳🇱',
    'NO' => 'Norway 🇳🇴',
    'NP' => 'Nepal 🇳🇵',
    'NR' => 'Nauru 🇳🇷',
    'NZ' => 'New Zealand 🇳🇿',
    // O
    'OM' => 'Oman 🇴🇲',
    // P
    'CP' => 'Clipperton Island  🇨🇵',
    'PK' => 'Pakistan 🇵🇰',
    'PA' => 'Panama 🇵🇦',
    'PE' => 'Peru 🇵🇪',
    'PH' => 'Philippines 🇵🇭',
    'PW' => 'Palau 🇵🇼',
    'PG' => 'Papua New Guinea 🇵🇬',
    'PL' => 'Poland 🇵🇱',
    'PR' => 'Puerto Rico 🇵🇷',
    'KP' => 'North Korea 🇰🇵',
    'PT' => 'Portugal 🇵🇹',
    'PY' => 'Paraguay 🇵🇾',
    'PS' => 'West Bank and Gaza',
    'PF' => 'French Polynesia 🇵🇫',
    // Q
    'QA' => 'Qatar 🇶🇦',
    // R
    'RO' => 'Romania 🇷🇴',
    'RU' => 'Russian Federation 🇷🇺',
    'RW' => 'Rwanda 🇷🇼',
    // S
    'SA' => 'Saudi Arabia 🇸🇦',
    'SD' => 'Sudan 🇸🇩',
    'SN' => 'Senegal 🇸🇳',
    'SG' => 'Singapore 🇸🇬',
    'SB' => 'Solomon Islands 🇸🇧',
    'SL' => 'Sierra Leone 🇸🇱',
    'SV' => 'El Salvador 🇸🇻',
    'SM' => 'San Marino 🇸🇲',
    'SO' => 'Somalia 🇸🇴',
    'RS' => 'Serbia 🇷🇸',
    'SS' => 'South Sudan 🇸🇸',
    'ST' => 'Sao Tome and Principe',
    'SR' => 'Suriname 🇸🇷',
    'SK' => 'Slovak Republic 🇸🇰',
    'SI' => 'Slovenia 🇸🇮',
    'SE' => 'Sweden 🇸🇪',
    'SZ' => 'Eswatini 🇸🇿',
    'SX' => 'Sint Maarten (Dutch part) 🇸🇽',
    'SC' => 'Seychelles 🇸🇨',
    'SY' => 'Syrian Arab Republic 🇸🇾',
    // T
    'TC' => 'Turks and Caicos Islands 🇹🇨',
    'TD' => 'Chad 🇹🇩',
    'TG' => 'Togo 🇹🇬',
    'TH' => 'Thailand 🇹🇭',
    'TJ' => 'Tajikistan 🇹🇯',
    'TM' => 'Turkmenistan 🇹🇲',
    'TL' => 'Timor-Leste 🇹🇱',
    'TO' => 'Tonga 🇹🇴',
    'TT' => 'Trinidad and Tobago 🇹🇹',
    'TN' => 'Tunisia 🇹🇳',
    'TR' => 'Turkey 🇹🇷',
    'TV' => 'Tuvalu 🇹🇻',
    'TW' => 'Taiwan 🇹🇼',
    'TZ' => 'Tanzania 🇹🇿',
    // U
    'UG' => 'Uganda 🇺🇬',
    'UA' => 'Ukraine 🇺🇦',
    'UY' => 'Uruguay 🇺🇾',
    'US' => 'United States of America 🇺🇸',
    'UZ' => 'Uzbekistan 🇺🇿',
    // V
    'VC' => 'St. Vincent and the Grenadines 🇻🇨',
    'VE' => 'Venezuela 🇻🇪',
    'VG' => 'British Virgin Islands 🇻🇬',
    'VI' => 'Virgin Islands (U.S.A.) 🇻🇮',
    'VN' => 'Vietnam 🇻🇳',
    'VU' => 'Vanuatu 🇻🇺',
    // W
    'WS' => 'Samoa 🇼🇸',
    // X
    'XK' => 'Kosovo 🇽🇰',
    // Y
    'YE' => 'Yemen, Rep. 🇾🇪',
    // Z
    'ZA' => 'South Africa 🇿🇦',
    'ZM' => 'Zambia 🇿🇲',
    'ZW' => 'Zimbabwe 🇿🇼',
);

?>